import express from 'express';
import mongoose from 'mongoose';
import cron from 'node-cron';
import { requireAuth } from '../middleware/auth.js';
import { requireRole } from '../middleware/roles.js';
import BackupRecord from '../models/BackupRecord.js';
import BackupSchedule from '../models/BackupSchedule.js';
import RestoreRecord from '../models/RestoreRecord.js';
import BackupStorageConfiguration from '../models/BackupStorageConfiguration.js';
import { refreshBackupConfiguration } from '../services/backup/backupConfiguration.js';
import { requestBackup } from '../services/backup/backupOrchestratorService.js';
import { requestRestorePreview, requestRestoreApproval, approveRestore, requestRestoreExecution } from '../services/backup/restoreOrchestratorService.js';
import { getBackupCostSummary } from '../services/backup/backupCostService.js';
import { getBackupDownloadUrl } from '../services/backup/s3StorageProvider.js';
import { enqueue, getBackupQueue, QUEUES } from '../services/backup/backupQueueService.js';
import { runBackupRetention } from '../services/backup/backupRetentionService.js';

const context = (req) => ({ idempotencyKey: req.get('idempotency-key'), requestId: req.get('x-request-id') || '', ip: req.ip, userAgent: req.get('user-agent') || '', method: req.method, path: req.originalUrl });
const page = (value, fallback) => Math.max(1, Number.parseInt(value, 10) || fallback);
const visibleBackupFilter = (actor) => actor.role === 'SUPER_ADMIN' ? {} : { tenantId: actor.tenantId };
const visibleRestoreFilter = (actor) => actor.role === 'SUPER_ADMIN' ? {} : { targetTenantId: actor.tenantId };
const ensureBackupScope = (backup, actor) => { if (!backup) return false; return actor.role === 'SUPER_ADMIN' || String(backup.tenantId || '') === String(actor.tenantId || ''); };
const sendQueued = (res, kind, record, replayed) => res.status(202).json({ success: true, [kind]: record, jobId: record.jobId, status: record.status, replayed });
const publicIdFilter = (value, field = 'uniqueId') => mongoose.isValidObjectId(value) ? { $or: [{ _id: value }, { [field]: value }] } : { [field]: value };

const backupRouter = (role) => {
  const router = express.Router(); const isTenant = role === 'TENANT_ADMIN'; router.use(requireAuth, requireRole(role));
  router.get('/', async (req, res, next) => { try { const limit = Math.min(page(req.query.limit, 25), 100); const currentPage = page(req.query.page, 1); const filter = { ...visibleBackupFilter(req.user), ...(req.query.status ? { status: String(req.query.status).toUpperCase() } : {}) }; const [items, total] = await Promise.all([BackupRecord.find(filter).sort({ createdAt: -1 }).skip((currentPage - 1) * limit).limit(limit).lean(), BackupRecord.countDocuments(filter)]); res.json({ success: true, backups: items, pagination: { page: currentPage, limit, total, pages: Math.ceil(total / limit) } }); } catch (error) { next(error); } });
  router.get('/storage-summary', async (req, res, next) => { try { const filter = { ...visibleBackupFilter(req.user), status: 'COMPLETED', deletedAt: null }; const [summary] = await BackupRecord.aggregate([{ $match: filter }, { $group: { _id: null, bytes: { $sum: '$compressedSizeBytes' }, transferredBytes: { $sum: '$compressedSizeBytes' }, count: { $sum: 1 } } }]); res.json({ success: true, retainedStorageBytes: summary?.bytes || 0, dataTransferredBytes: summary?.transferredBytes || 0, backupCount: summary?.count || 0 }); } catch (error) { next(error); } });
  router.get('/cost-summary', async (req, res, next) => { try { res.json({ success: true, ...(await getBackupCostSummary({ tenantId: isTenant ? req.user.tenantId : null })) }); } catch (error) { next(error); } });
  router.post('/', async (req, res, next) => { try { const result = await requestBackup({ actor: req.user, request: isTenant ? { ...req.body, scopeType: req.body?.scopeType || 'TENANT', tenantId: req.user.tenantId } : req.body, context: context(req) }); sendQueued(res, 'backup', result.backup, result.replayed); } catch (error) { next(error); } });
  router.get('/:backupId', async (req, res, next) => { try { const backup = await BackupRecord.findOne({ ...visibleBackupFilter(req.user), ...publicIdFilter(req.params.backupId) }).lean(); if (!backup) return res.status(404).json({ success: false, error: 'Backup not found.' }); res.json({ success: true, backup }); } catch (error) { next(error); } });
  router.post('/:backupId/verify', async (req, res, next) => { try { const backup = await BackupRecord.findOne({ ...visibleBackupFilter(req.user), ...publicIdFilter(req.params.backupId) }); if (!backup) return res.status(404).json({ success: false, error: 'Backup not found.' }); const jobId = `backup-verify-${backup._id}-${Date.now()}`; await enqueue({ queue: QUEUES.VERIFY, jobName: 'verify-backup', jobId, data: { backupId: String(backup._id) } }); await backup.updateOne({ $set: { status: 'VERIFYING', jobId } }); res.status(202).json({ success: true, jobId, status: 'QUEUED' }); } catch (error) { next(error); } });
  router.post('/:backupId/cancel', async (req, res, next) => { try { const backup = await BackupRecord.findOne({ ...visibleBackupFilter(req.user), ...publicIdFilter(req.params.backupId) }); if (!backup) return res.status(404).json({ success: false, error: 'Backup not found.' }); if (!['QUEUED', 'PREPARING'].includes(backup.status)) return res.status(409).json({ success: false, error: 'Only a queued backup can be cancelled.' }); if (backup.jobId) { for (const queueName of [QUEUES.PLATFORM, QUEUES.TENANT, QUEUES.INCREMENTAL]) { const job = await getBackupQueue(queueName).getJob(backup.jobId); if (job) await job.remove(); } } await backup.updateOne({ $set: { status: 'CANCELLED' } }); res.json({ success: true, status: 'CANCELLED' }); } catch (error) { next(error); } });
  router.get('/:backupId/download-url', async (req, res, next) => { try { const backup = await BackupRecord.findOne({ ...visibleBackupFilter(req.user), ...publicIdFilter(req.params.backupId) }); if (!backup || backup.status !== 'COMPLETED') return res.status(404).json({ success: false, error: 'Completed backup not found.' }); res.json({ success: true, url: await getBackupDownloadUrl({ key: backup.s3ObjectKey, filename: `${backup.uniqueId}.enc` }), expiresInSeconds: Number(process.env.BACKUP_SIGNED_URL_EXPIRY_SECONDS || 300) }); } catch (error) { next(error); } });
  router.delete('/:backupId', async (req, res, next) => { try { const backup = await BackupRecord.findOne({ ...visibleBackupFilter(req.user), ...publicIdFilter(req.params.backupId) }); if (!backup) return res.status(404).json({ success: false, error: 'Backup not found.' }); await backup.updateOne({ $set: { expiresAt: new Date(), status: 'EXPIRED' } }); const jobId = `backup-retention-${backup._id}-${Date.now()}`; await enqueue({ queue: QUEUES.RETENTION, jobName: 'retention-cleanup', jobId, data: {} }); res.status(202).json({ success: true, jobId, status: 'DELETING' }); } catch (error) { next(error); } });
  return router;
};

const scheduleRouter = (role) => {
  const router = express.Router(); const isTenant = role === 'TENANT_ADMIN'; router.use(requireAuth, requireRole(role)); const scope = (req) => isTenant ? { tenantId: req.user.tenantId } : {};
  router.get('/', async (req, res, next) => { try { res.json({ success: true, schedules: await BackupSchedule.find(scope(req)).sort({ createdAt: -1 }).lean() }); } catch (error) { next(error); } });
  router.post('/', async (req, res, next) => { try { const expression = String(req.body?.cronExpression || '').trim(); if (!cron.validate(expression)) return res.status(400).json({ success: false, error: 'A valid cronExpression is required.' }); const schedule = await BackupSchedule.create({ ...req.body, tenantId: isTenant ? req.user.tenantId : req.body.tenantId || null, scopeType: isTenant ? 'TENANT' : req.body.scopeType, createdBy: req.user._id, updatedBy: req.user._id }); res.status(201).json({ success: true, schedule }); } catch (error) { next(error); } });
  router.get('/:scheduleId', async (req, res, next) => { try { const schedule = await BackupSchedule.findOne({ _id: req.params.scheduleId, ...scope(req) }); if (!schedule) return res.status(404).json({ success: false, error: 'Schedule not found.' }); res.json({ success: true, schedule }); } catch (error) { next(error); } });
  router.put('/:scheduleId', async (req, res, next) => { try { if (req.body?.cronExpression && !cron.validate(String(req.body.cronExpression))) return res.status(400).json({ success: false, error: 'Invalid cronExpression.' }); const schedule = await BackupSchedule.findOneAndUpdate({ _id: req.params.scheduleId, ...scope(req) }, { $set: { ...req.body, tenantId: isTenant ? req.user.tenantId : req.body.tenantId, updatedBy: req.user._id } }, { new: true, runValidators: true }); if (!schedule) return res.status(404).json({ success: false, error: 'Schedule not found.' }); res.json({ success: true, schedule }); } catch (error) { next(error); } });
  router.delete('/:scheduleId', async (req, res, next) => { try { const schedule = await BackupSchedule.findOneAndDelete({ _id: req.params.scheduleId, ...scope(req) }); if (!schedule) return res.status(404).json({ success: false, error: 'Schedule not found.' }); res.status(204).end(); } catch (error) { next(error); } });
  const toggle = (enabled) => async (req, res, next) => { try { const schedule = await BackupSchedule.findOneAndUpdate({ _id: req.params.scheduleId, ...scope(req) }, { $set: { enabled, updatedBy: req.user._id } }, { new: true }); if (!schedule) return res.status(404).json({ success: false, error: 'Schedule not found.' }); res.json({ success: true, schedule }); } catch (error) { next(error); } };
  router.post('/:scheduleId/enable', toggle(true)); router.post('/:scheduleId/disable', toggle(false));
  router.get('/:scheduleId/history', async (req, res, next) => { try { const schedule = await BackupSchedule.findOne({ _id: req.params.scheduleId, ...scope(req) }); if (!schedule) return res.status(404).json({ success: false, error: 'Schedule not found.' }); res.json({ success: true, backups: await BackupRecord.find({ scheduleId: schedule._id }).sort({ createdAt: -1 }).limit(100).lean() }); } catch (error) { next(error); } });
  router.post('/:scheduleId/run', async (req, res, next) => { try { const schedule = await BackupSchedule.findOne({ _id: req.params.scheduleId, ...scope(req) }); if (!schedule) return res.status(404).json({ success: false, error: 'Schedule not found.' }); const result = await requestBackup({ actor: req.user, request: { backupType: schedule.backupType, scopeType: schedule.scopeType, tenantId: schedule.tenantId, subTenantId: schedule.subTenantId, examId: schedule.examId, scheduleId: schedule._id, verificationLevel: schedule.verificationLevel, storageClass: schedule.storageClass, retentionPolicy: schedule.retentionPolicy, includeCollections: schedule.includeCollections, excludeCollections: schedule.excludeCollections, name: schedule.name }, context: context(req) }); sendQueued(res, 'backup', result.backup, result.replayed); } catch (error) { next(error); } });
  return router;
};

const restoreRouter = (role) => { const router = express.Router(); const isTenant = role === 'TENANT_ADMIN'; router.use(requireAuth, requireRole(role)); const scope = (req) => visibleRestoreFilter(req.user);
  router.get('/', async (req, res, next) => { try { res.json({ success: true, restores: await RestoreRecord.find(scope(req)).sort({ createdAt: -1 }).lean() }); } catch (error) { next(error); } });
  router.post('/preview', async (req, res, next) => { try { const result = await requestRestorePreview({ actor: req.user, request: req.body, context: context(req) }); sendQueued(res, 'restore', result.restore, result.replayed); } catch (error) { next(error); } });
  router.get('/:restoreId', async (req, res, next) => { try { const restore = await RestoreRecord.findOne({ _id: req.params.restoreId, ...scope(req) }).populate('backupId').lean(); if (!restore) return res.status(404).json({ success: false, error: 'Restore not found.' }); res.json({ success: true, restore }); } catch (error) { next(error); } });
  router.post('/:restoreId/request-approval', async (req, res, next) => { try { res.json({ success: true, ...(await requestRestoreApproval({ actor: req.user, restoreId: req.params.restoreId, comments: req.body?.comments })) }); } catch (error) { next(error); } });
  if (!isTenant) { router.post('/:restoreId/approve', async (req, res, next) => { try { res.json({ success: true, restore: await approveRestore({ actor: req.user, restoreId: req.params.restoreId, approved: true, comments: req.body?.comments }) }); } catch (error) { next(error); } }); router.post('/:restoreId/reject', async (req, res, next) => { try { res.json({ success: true, restore: await approveRestore({ actor: req.user, restoreId: req.params.restoreId, approved: false, comments: req.body?.comments }) }); } catch (error) { next(error); } }); }
  router.post('/:restoreId/execute', async (req, res, next) => { try { const restore = await requestRestoreExecution({ actor: req.user, restoreId: req.params.restoreId, mfaVerified: String(req.get('x-mfa-verified') || '').toLowerCase() === 'true' && Boolean(req.user?.mfaVerifiedAt) }); sendQueued(res, 'restore', restore, false); } catch (error) { next(error); } });
  router.post('/:restoreId/cancel', async (req, res, next) => { try { const restore = await RestoreRecord.findOne({ _id: req.params.restoreId, ...scope(req) }); if (!restore) return res.status(404).json({ success: false, error: 'Restore not found.' }); if (!['DRAFT', 'QUEUED', 'PREVIEW_READY', 'AWAITING_APPROVAL', 'APPROVED'].includes(restore.status)) return res.status(409).json({ success: false, error: 'Restore cannot be cancelled after execution begins.' }); await restore.updateOne({ $set: { status: 'CANCELLED' } }); res.json({ success: true, status: 'CANCELLED' }); } catch (error) { next(error); } });
  return router; };

export const superAdminBackupsRouter = backupRouter('SUPER_ADMIN'); export const tenantAdminBackupsRouter = backupRouter('TENANT_ADMIN'); export const superAdminBackupSchedulesRouter = scheduleRouter('SUPER_ADMIN'); export const tenantAdminBackupSchedulesRouter = scheduleRouter('TENANT_ADMIN'); export const superAdminRestoresRouter = restoreRouter('SUPER_ADMIN'); export const tenantAdminRestoresRouter = restoreRouter('TENANT_ADMIN');
export const backupStorageSettingsRouter = express.Router();
backupStorageSettingsRouter.use(requireAuth, requireRole('SUPER_ADMIN'));
backupStorageSettingsRouter.get('/', async (_req, res, next) => { try { const configuration = await BackupStorageConfiguration.findOne({ environment: 'default' }).lean(); res.json({ success: true, configuration: configuration || { environment: 'default', enabled: false, provider: 's3', region: 'ap-south-1', defaultStorageClass: 'STANDARD', applicationEncryptionEnabled: true, signedUrlExpirySeconds: 300, objectPrefix: 'xamigo-backups', queuePrefix: 'xamigo', pricingConfiguration: { currency: 'INR', standardPerGbMonth: 2.1 } } }); } catch (error) { next(error); } });
backupStorageSettingsRouter.put('/', async (req, res, next) => { try { const body = req.body || {}; const allowed = ['enabled', 'provider', 'bucket', 'region', 'endpoint', 'forcePathStyle', 'defaultStorageClass', 'kmsKeyId', 'applicationEncryptionEnabled', 'signedUrlExpirySeconds', 'objectPrefix', 'queuePrefix', 'tenantSelfServiceRestoreEnabled', 'pricingConfiguration', 'lifecycleConfiguration']; const update = Object.fromEntries(allowed.filter((key) => Object.prototype.hasOwnProperty.call(body, key)).map((key) => [key, body[key]])); const current = await BackupStorageConfiguration.findOne({ environment: 'default' }).lean(); const nextConfiguration = { ...(current || {}), ...update }; if (nextConfiguration.provider && String(nextConfiguration.provider).toLowerCase() !== 's3') return res.status(400).json({ success: false, error: 'Only S3-compatible storage is supported.' }); if (nextConfiguration.enabled && (!nextConfiguration.bucket || (nextConfiguration.applicationEncryptionEnabled !== false && !nextConfiguration.kmsKeyId))) return res.status(400).json({ success: false, error: 'Bucket and KMS key ID are required before enabling backup storage.' }); const configuration = await BackupStorageConfiguration.findOneAndUpdate({ environment: 'default' }, { $set: update, $setOnInsert: { environment: 'default' } }, { upsert: true, new: true, runValidators: true }); await refreshBackupConfiguration(); res.json({ success: true, configuration }); } catch (error) { next(error); } });
export const backupJobsRouter = express.Router();
backupJobsRouter.get('/:jobId', requireAuth, async (req, res, next) => { try { const backup = await BackupRecord.findOne({ jobId: req.params.jobId }); const restore = backup ? null : await RestoreRecord.findOne({ jobId: req.params.jobId }); const record = backup || restore; if (!record || (req.user.role !== 'SUPER_ADMIN' && String(record.tenantId || record.targetTenantId || '') !== String(req.user.tenantId))) return res.status(404).json({ success: false, error: 'Job not found.' }); res.json({ success: true, jobId: req.params.jobId, status: record.status, progress: record.metadata?.progress || 0, progressMessage: record.metadata?.progressMessage || '', updatedAt: record.updatedAt }); } catch (error) { next(error); } });
backupJobsRouter.get('/:jobId/events', requireAuth, async (req, res, next) => { try { const backup = await BackupRecord.findOne({ jobId: req.params.jobId }); const restore = backup ? null : await RestoreRecord.findOne({ jobId: req.params.jobId }); const record = backup || restore; if (!record || (req.user.role !== 'SUPER_ADMIN' && String(record.tenantId || record.targetTenantId || '') !== String(req.user.tenantId))) return res.status(404).json({ success: false, error: 'Job not found.' }); res.json({ success: true, events: [{ at: record.updatedAt, status: record.status, progress: record.metadata?.progress || 0, message: record.metadata?.progressMessage || record.failureMessage || '' }] }); } catch (error) { next(error); } });
backupJobsRouter.post('/:jobId/cancel', requireAuth, async (req, res, next) => { try { const backup = await BackupRecord.findOne({ jobId: req.params.jobId }); const restore = backup ? null : await RestoreRecord.findOne({ jobId: req.params.jobId }); const record = backup || restore; if (!record || (req.user.role !== 'SUPER_ADMIN' && String(record.tenantId || record.targetTenantId || '') !== String(req.user.tenantId))) return res.status(404).json({ success: false, error: 'Job not found.' }); if (!['QUEUED', 'PREPARING', 'ANALYZING', 'PREVIEW_READY', 'AWAITING_APPROVAL'].includes(record.status)) return res.status(409).json({ success: false, error: 'Job cannot be cancelled after execution begins.' }); await record.updateOne({ $set: { status: 'CANCELLED' } }); res.json({ success: true, status: 'CANCELLED' }); } catch (error) { next(error); } });
