import cron from 'node-cron';
import IORedis from 'ioredis';
import BackupSchedule from '../../models/BackupSchedule.js';
import User from '../../models/User.js';
import { requestBackup } from './backupOrchestratorService.js';
import { getBackupConfiguration } from './backupConfiguration.js';

const tasks = new Map(); let refreshTimer;
const minuteKey = () => new Date().toISOString().slice(0, 16);
const runSchedule = async (scheduleId) => {
  const schedule = await BackupSchedule.findById(scheduleId); if (!schedule?.enabled) return; const actor = await User.findById(schedule.createdBy).select('_id role tenantId'); if (!actor) throw new Error('Schedule creator is no longer available.');
  const config = getBackupConfiguration(); const redis = new IORedis(config.redisUrl, { maxRetriesPerRequest: null, enableReadyCheck: false }); const lockKey = `backup:schedule:${schedule._id}:${minuteKey()}`; try { if (!await redis.set(lockKey, '1', 'PX', 55 * 60 * 1000, 'NX')) return; const result = await requestBackup({ actor, request: { backupType: schedule.backupType, scopeType: schedule.scopeType, tenantId: schedule.tenantId, subTenantId: schedule.subTenantId, examId: schedule.examId, scheduleId: schedule._id, name: schedule.name, description: schedule.description, verificationLevel: schedule.verificationLevel, storageClass: schedule.storageClass, retentionPolicy: schedule.retentionPolicy, includeCollections: schedule.includeCollections, excludeCollections: schedule.excludeCollections }, context: { idempotencyKey: `schedule-${schedule._id}-${minuteKey()}`, requestId: `schedule-${schedule._id}` } }); await schedule.updateOne({ $set: { lastRunAt: new Date(), lastRunStatus: result.backup.status, consecutiveFailureCount: 0 } }); } catch (error) { await schedule.updateOne({ $set: { lastRunAt: new Date(), lastRunStatus: 'FAILED' }, $inc: { consecutiveFailureCount: 1 } }); throw error; } finally { await redis.quit(); } };
const refreshSchedules = async () => { const schedules = await BackupSchedule.find({ enabled: true }).select('_id cronExpression timezone updatedAt').lean(); const active = new Set(schedules.map((item) => String(item._id))); for (const [id, entry] of tasks) if (!active.has(id) || entry.expression !== schedules.find((item) => String(item._id) === id)?.cronExpression) { entry.task.stop(); tasks.delete(id); } for (const schedule of schedules) { const id = String(schedule._id); if (tasks.has(id) || !cron.validate(schedule.cronExpression)) continue; const task = cron.schedule(schedule.cronExpression, () => { runSchedule(id).catch((error) => console.error(`[backup-schedule] ${id} failed:`, error.message || error)); }, { timezone: schedule.timezone || 'Asia/Kolkata', noOverlap: true }); tasks.set(id, { task, expression: schedule.cronExpression }); } };
export const startBackupScheduleService = () => { if (!getBackupConfiguration().enabled) return; void refreshSchedules(); refreshTimer = setInterval(() => void refreshSchedules().catch((error) => console.error('[backup-schedule] refresh failed:', error.message || error)), 60_000); };
export const stopBackupScheduleService = () => { if (refreshTimer) clearInterval(refreshTimer); refreshTimer = null; for (const { task } of tasks.values()) task.stop(); tasks.clear(); };
