import BackupStorageConfiguration from '../../models/BackupStorageConfiguration.js';

const integer = (value, fallback) => { const parsed = Number.parseInt(value, 10); return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback; };
const defaults = Object.freeze({ enabled: false, provider: 's3', bucket: '', region: 'ap-south-1', endpoint: '', forcePathStyle: false, defaultStorageClass: 'STANDARD', kmsKeyId: '', applicationEncryptionEnabled: true, signedUrlExpirySeconds: 300, objectPrefix: 'xamigo-backups', queuePrefix: 'xamigo', tenantSelfServiceRestoreEnabled: false, currency: 'INR', storageRatePerGbMonth: 2.1, environment: process.env.NODE_ENV || 'development', redisUrl: process.env.REDIS_URL || '' });
let cachedConfiguration = { ...defaults };

const normalize = (record) => ({ ...defaults, enabled: Boolean(record?.enabled), provider: String(record?.provider || defaults.provider).toLowerCase(), bucket: String(record?.bucket || '').trim(), region: String(record?.region || defaults.region).trim(), endpoint: String(record?.endpoint || '').trim(), forcePathStyle: Boolean(record?.forcePathStyle), defaultStorageClass: String(record?.defaultStorageClass || defaults.defaultStorageClass).trim(), kmsKeyId: String(record?.kmsKeyId || '').trim(), applicationEncryptionEnabled: record?.applicationEncryptionEnabled !== false, signedUrlExpirySeconds: Math.min(integer(record?.signedUrlExpirySeconds, 300), 900), objectPrefix: String(record?.objectPrefix || defaults.objectPrefix).replace(/^\/+|\/+$/g, ''), queuePrefix: String(record?.queuePrefix || defaults.queuePrefix).trim(), tenantSelfServiceRestoreEnabled: Boolean(record?.tenantSelfServiceRestoreEnabled), currency: String(record?.pricingConfiguration?.currency || defaults.currency).trim(), storageRatePerGbMonth: Number(record?.pricingConfiguration?.standardPerGbMonth) || defaults.storageRatePerGbMonth });
export const refreshBackupConfiguration = async () => { const record = await BackupStorageConfiguration.findOne({ environment: 'default' }).lean(); cachedConfiguration = normalize(record); return cachedConfiguration; };
export const getBackupConfiguration = () => cachedConfiguration;
export const assertBackupConfiguration = ({ requireEnabled = true } = {}) => { const configuration = getBackupConfiguration(); if (requireEnabled && !configuration.enabled) throw Object.assign(new Error('Backup storage has not been enabled in Super Admin storage settings.'), { code: 'BACKUP_DISABLED' }); if (configuration.provider !== 's3') throw Object.assign(new Error('Only S3-compatible storage is supported.'), { code: 'BACKUP_PROVIDER_INVALID' }); if (!configuration.bucket || !configuration.redisUrl) throw Object.assign(new Error('Configure a bucket in Backup Storage Settings and ensure the worker has Redis deployment connectivity.'), { code: 'BACKUP_CONFIGURATION_INVALID' }); if (configuration.applicationEncryptionEnabled && !configuration.kmsKeyId) throw Object.assign(new Error('KMS key ID is required when application encryption is enabled.'), { code: 'BACKUP_KMS_CONFIGURATION_INVALID' }); return configuration; };
