import fs from 'node:fs/promises';
import path from 'node:path';
import { createHash, randomUUID } from 'node:crypto';
import IORedis from 'ioredis';
import { Worker } from 'bullmq';
import BackupRecord from '../../models/BackupRecord.js';
import { exportBackupPackage } from './backupExportService.js';
import { encryptBackupPayload } from './backupEncryptionService.js';
import { uploadBackupObject } from './s3StorageProvider.js';
import { verifyBackupObject } from './backupVerificationService.js';
import { runBackupRetention } from './backupRetentionService.js';
import { getBackupConfiguration, refreshBackupConfiguration } from './backupConfiguration.js';
import { getQueueConnection, QUEUES } from './backupQueueService.js';
import { logAuditEvent } from '../../utils/auditLogger.js';

const workerConnection = () => getQueueConnection();
const backupObjectKey = (backup) => { const date = new Date(); const datePath = [date.getUTCFullYear(), String(date.getUTCMonth() + 1).padStart(2, '0'), String(date.getUTCDate()).padStart(2, '0')].join('/'); const root = `${getBackupConfiguration().objectPrefix}/${getBackupConfiguration().environment}`; if (backup.scopeType === 'PLATFORM') return `${root}/platform/full/${datePath}/${backup.uniqueId}/backup.enc`; if (backup.scopeType === 'EXAM') return `${root}/exams/${backup.tenantId}/${backup.examId}/${datePath}/${backup.uniqueId}/backup.enc`; const type = backup.backupType === 'INCREMENTAL' ? 'incremental' : backup.backupType === 'METADATA_ONLY' ? 'metadata' : 'full'; return `${root}/tenants/${backup.tenantId}/${type}/${datePath}/${backup.uniqueId}/backup.enc`; };
const updateProgress = async (backup, percent, message) => { await BackupRecord.updateOne({ _id: backup._id }, { $set: { 'metadata.progress': Math.min(100, Math.max(0, percent)), 'metadata.progressMessage': message, 'metadata.progressUpdatedAt': new Date() } }); };
const withLock = async (key, callback) => { const config = getBackupConfiguration(); const redis = new IORedis(config.redisUrl, { maxRetriesPerRequest: null, enableReadyCheck: false }); const value = randomUUID(); const acquired = await redis.set(key, value, 'PX', 60 * 60 * 1000, 'NX'); if (!acquired) { await redis.quit(); throw Object.assign(new Error('A backup or restore is already running for this scope.'), { code: 'SCOPE_LOCKED' }); } try { return await callback(); } finally { await redis.eval("if redis.call('get', KEYS[1]) == ARGV[1] then return redis.call('del', KEYS[1]) else return 0 end", 1, key, value).catch(() => {}); await redis.quit(); } };

export const executeBackupRecord = async (backupId, job = null) => {
  await refreshBackupConfiguration();
  const backup = await BackupRecord.findById(backupId); if (!backup) throw new Error('Backup record not found.'); if (backup.status === 'COMPLETED') return backup; if (backup.status === 'CANCELLED' || backup.status === 'DELETED') throw new Error(`Backup is ${backup.status.toLowerCase()}.`);
  const lock = backup.scopeType === 'PLATFORM' ? 'backup:platform' : `backup:tenant:${backup.tenantId}`;
  return withLock(lock, async () => {
    let packageInfo; try {
      await backup.updateOne({ $set: { status: 'PREPARING', startedAt: backup.startedAt || new Date(), failureCode: '', failureMessage: '' } }); await updateProgress(backup, 5, 'Preparing export'); if (job) await job.updateProgress(5);
      await backup.updateOne({ $set: { status: 'EXPORTING' } }); packageInfo = await exportBackupPackage({ backup, onProgress: async (percent, message) => { await updateProgress(backup, percent, message); if (job) await job.updateProgress(percent); } });
      await backup.updateOne({ $set: { status: 'ENCRYPTING' } }); await updateProgress(backup, 75, 'Encrypting backup'); const compressed = await fs.readFile(packageInfo.archivePath); const encryptedInfo = await encryptBackupPayload(compressed, backup.uniqueId); const checksum = createHash('sha256').update(encryptedInfo.encrypted).digest('hex');
      const objectKey = backupObjectKey(backup); const manifestKey = objectKey.replace(/backup\.enc$/, 'manifest.json'); await backup.updateOne({ $set: { status: 'UPLOADING' } }); await updateProgress(backup, 82, 'Uploading encrypted backup'); const upload = await uploadBackupObject({ key: objectKey, body: encryptedInfo.encrypted, storageClass: backup.s3StorageClass, metadata: { backupid: backup.uniqueId, checksum, encryption: encryptedInfo.metadata.encryptionMode || 'NONE' } }); await uploadBackupObject({ key: manifestKey, body: JSON.stringify(packageInfo.manifest), contentType: 'application/json', storageClass: backup.s3StorageClass, metadata: { backupid: backup.uniqueId } });
      await backup.updateOne({ $set: { status: 'VERIFYING', s3Provider: 's3', s3Bucket: upload.bucket, s3Region: getBackupConfiguration().region, s3ObjectKey: objectKey, s3VersionId: upload.versionId, s3ETag: upload.eTag, checksum, compressedSizeBytes: encryptedInfo.encrypted.length, uncompressedSizeBytes: packageInfo.uncompressedSizeBytes, collectionsIncluded: packageInfo.manifest.collections, collectionsExcluded: packageInfo.manifest.excludedCollections, recordCounts: packageInfo.recordCounts, totalRecords: Object.values(packageInfo.recordCounts).reduce((total, count) => total + count, 0), ...encryptedInfo.metadata, 'metadata.manifestObjectKey': manifestKey } });
      const refreshed = await BackupRecord.findById(backup._id); const verification = await verifyBackupObject({ backup: refreshed, level: backup.verificationLevel }); await backup.updateOne({ $set: { status: 'COMPLETED', verificationStatus: 'PASSED', completedAt: new Date(), verifiedAt: new Date(), 'metadata.verification': verification, 'metadata.progress': 100, 'metadata.progressMessage': 'Backup complete' } }); if (job) await job.updateProgress(100);
      const completed = await BackupRecord.findById(backup._id); logAuditEvent('BACKUP_COMPLETED', { userId: backup.initiatedBy, userRole: backup.initiatedByRole, tenantId: backup.tenantId, resourceType: 'BackupRecord', resourceId: backup._id, backupId: backup.uniqueId, jobId: backup.jobId, result: 'COMPLETED', recordCounts: packageInfo.recordCounts }); return completed;
    } catch (error) { await BackupRecord.updateOne({ _id: backup._id }, { $set: { status: 'FAILED', verificationStatus: 'FAILED', failureCode: error.code || 'BACKUP_EXECUTION_FAILED', failureMessage: String(error.message || error).slice(0, 1000), failureDetails: { name: error.name } } }); logAuditEvent('BACKUP_FAILED', { userId: backup.initiatedBy, userRole: backup.initiatedByRole, tenantId: backup.tenantId, resourceType: 'BackupRecord', resourceId: backup._id, backupId: backup.uniqueId, jobId: backup.jobId, result: 'FAILED', failureReason: String(error.message || error).slice(0, 1000) }); throw error; } finally { if (packageInfo?.workspace) await fs.rm(packageInfo.workspace, { recursive: true, force: true }); }
  });
};
const runVerification = async (backupId) => { const backup = await BackupRecord.findById(backupId); if (!backup) throw new Error('Backup record not found.'); await backup.updateOne({ $set: { status: 'VERIFYING', verificationStatus: 'PENDING' } }); try { const verification = await verifyBackupObject({ backup, level: backup.verificationLevel }); await backup.updateOne({ $set: { status: 'COMPLETED', verificationStatus: 'PASSED', verifiedAt: new Date(), 'metadata.verification': verification } }); } catch (error) { await backup.updateOne({ $set: { status: 'FAILED', verificationStatus: 'FAILED', failureCode: 'VERIFICATION_FAILED', failureMessage: String(error.message || error).slice(0, 1000) } }); throw error; } };
export const createBackupWorkers = () => { const config = getBackupConfiguration(); const options = (concurrency) => ({ connection: workerConnection().duplicate(), prefix: config.queuePrefix, concurrency, lockDuration: 120000 }); const make = (queue, concurrency) => new Worker(queue, async (job) => executeBackupRecord(job.data.backupId, job), options(concurrency)); return [make(QUEUES.PLATFORM, 1), make(QUEUES.TENANT, 3), make(QUEUES.INCREMENTAL, 3), new Worker(QUEUES.VERIFY, (job) => runVerification(job.data.backupId), options(1)), new Worker(QUEUES.RETENTION, () => runBackupRetention(), options(1))]; };
