import { randomUUID } from 'node:crypto';
import mongoose from 'mongoose';
import BackupRecord from '../../models/BackupRecord.js';
import RestoreRecord from '../../models/RestoreRecord.js';
import RestoreApproval from '../../models/RestoreApproval.js';
import { assertBackupConfiguration, refreshBackupConfiguration, getBackupConfiguration } from './backupConfiguration.js';
import { enqueue, QUEUES } from './backupQueueService.js';
import { logAuditEvent } from '../../utils/auditLogger.js';

const restoreTypes = new Set(['FULL_PLATFORM', 'TENANT', 'SELECTIVE']); const modes = new Set(['REPLACE', 'MERGE', 'CLONE', 'PREVIEW_ONLY', 'SELECTED_COLLECTIONS']);
const selfServiceEnabled = () => getBackupConfiguration().tenantSelfServiceRestoreEnabled;
const authorizeRestore = ({ actor, backup, targetTenantId }) => {
  if (actor.role === 'SUPER_ADMIN') return;
  if (actor.role !== 'TENANT_ADMIN') throw Object.assign(new Error('Backup restore is restricted to administrators.'), { statusCode: 403 });
  if (!backup.tenantId || String(backup.tenantId) !== String(actor.tenantId) || String(targetTenantId || actor.tenantId) !== String(actor.tenantId)) throw Object.assign(new Error('Tenant Admin can restore only its own tenant backup into its own tenant.'), { statusCode: 403 });
};
export const requestRestorePreview = async ({ actor, request, context = {} }) => {
  await refreshBackupConfiguration(); assertBackupConfiguration(); const backupFilter = mongoose.isValidObjectId(request.backupId) ? { $or: [{ _id: request.backupId }, { uniqueId: request.backupId }] } : { uniqueId: request.backupId }; const backup = await BackupRecord.findOne(backupFilter); if (!backup || backup.status !== 'COMPLETED' || backup.verificationStatus !== 'PASSED') throw Object.assign(new Error('A completed, verified backup is required.'), { statusCode: 400 });
  const restoreType = String(request.restoreType || (backup.scopeType === 'PLATFORM' ? 'FULL_PLATFORM' : 'TENANT')).toUpperCase(); const restoreMode = String(request.restoreMode || 'PREVIEW_ONLY').toUpperCase(); if (!restoreTypes.has(restoreType) || !modes.has(restoreMode)) throw Object.assign(new Error('Invalid restore type or mode.'), { statusCode: 400 }); if (restoreMode === 'CLONE') throw Object.assign(new Error('Clone restore is not enabled until tenant ID and unique-field remapping is deployed.'), { statusCode: 501, code: 'CLONE_RESTORE_NOT_ENABLED' });
  const targetTenantId = actor.role === 'TENANT_ADMIN' ? actor.tenantId : request.targetTenantId || backup.tenantId || null; authorizeRestore({ actor, backup, targetTenantId }); if (restoreType === 'FULL_PLATFORM' && actor.role !== 'SUPER_ADMIN') throw Object.assign(new Error('Full-platform restore is Super Admin only.'), { statusCode: 403 });
  const idempotencyKey = String(context.idempotencyKey || request.idempotencyKey || randomUUID()); const existing = await RestoreRecord.findOne({ initiatedBy: actor._id, idempotencyKey }); if (existing) return { restore: existing, replayed: true };
  const needsApproval = restoreMode !== 'PREVIEW_ONLY'; const restore = await RestoreRecord.create({ backupId: backup._id, restoreType, scopeType: backup.scopeType, targetTenantId, targetSubTenantId: request.targetSubTenantId || null, targetExamId: request.targetExamId || null, restoreMode, conflictStrategy: String(request.conflictStrategy || 'KEEP_EXISTING').toUpperCase(), selectedCollections: request.selectedCollections || [], status: 'QUEUED', initiatedBy: actor._id, initiatedByRole: actor.role, idempotencyKey, requestedReason: String(request.reason || 'Restore preview requested.').slice(0, 2000), approvalStatus: needsApproval ? 'PENDING' : 'NOT_REQUIRED', metadata: { requestId: context.requestId || '', actorIp: context.ip || '', userAgent: context.userAgent || '', requiresMfa: restoreType === 'FULL_PLATFORM' } });
  const jobId = `restore-preview-${restore._id}`; await enqueue({ queue: QUEUES.RESTORE_PREVIEW, jobName: 'restore-preview', jobId, data: { restoreId: String(restore._id) } }); await restore.updateOne({ $set: { jobId } }); restore.jobId = jobId; logAuditEvent('RESTORE_PREVIEW_REQUESTED', { userId: actor._id, userRole: actor.role, tenantId: targetTenantId, resourceType: 'RestoreRecord', resourceId: restore._id, backupId: backup.uniqueId, restoreId: restore.uniqueId, jobId, ip: context.ip, userAgent: context.userAgent, requestId: context.requestId }); return { restore, replayed: false };
};
export const requestRestoreApproval = async ({ actor, restoreId, comments = '' }) => {
  const restore = await RestoreRecord.findById(restoreId); if (!restore) throw Object.assign(new Error('Restore request not found.'), { statusCode: 404 }); if (String(restore.initiatedBy) !== String(actor._id) && actor.role !== 'SUPER_ADMIN') throw Object.assign(new Error('Not authorized to request approval.'), { statusCode: 403 }); if (restore.status !== 'PREVIEW_READY') throw Object.assign(new Error('Restore preview must be ready before approval.'), { statusCode: 409 }); const approval = await RestoreApproval.findOneAndUpdate({ restoreId: restore._id }, { $setOnInsert: { requestedBy: restore.initiatedBy, requiredApproverRole: 'SUPER_ADMIN', requestedAt: new Date(), expiresAt: new Date(Date.now() + 24 * 3600000) }, $set: { status: 'PENDING', comments: String(comments).slice(0, 2000) } }, { upsert: true, new: true }); await restore.updateOne({ $set: { status: 'AWAITING_APPROVAL', approvalStatus: 'PENDING' } }); return { restore: await RestoreRecord.findById(restore._id), approval };
};
export const approveRestore = async ({ actor, restoreId, approved, comments = '' }) => {
  if (actor.role !== 'SUPER_ADMIN') throw Object.assign(new Error('Super Admin approval is required.'), { statusCode: 403 }); const restore = await RestoreRecord.findById(restoreId); if (!restore) throw Object.assign(new Error('Restore request not found.'), { statusCode: 404 }); const status = approved ? 'APPROVED' : 'REJECTED'; await RestoreApproval.findOneAndUpdate({ restoreId: restore._id }, { $set: { status, approvedBy: actor._id, approvedAt: new Date(), comments: String(comments).slice(0, 2000) } }, { upsert: true }); await restore.updateOne({ $set: { status: approved ? 'APPROVED' : 'CANCELLED', approvalStatus: status, approvedBy: actor._id, approvalReason: String(comments).slice(0, 2000) } }); return RestoreRecord.findById(restore._id);
};
export const requestRestoreExecution = async ({ actor, restoreId, mfaVerified = false }) => {
  await refreshBackupConfiguration(); assertBackupConfiguration(); const restore = await RestoreRecord.findById(restoreId).populate('backupId'); if (!restore) throw Object.assign(new Error('Restore request not found.'), { statusCode: 404 }); authorizeRestore({ actor, backup: restore.backupId, targetTenantId: restore.targetTenantId }); if (restore.restoreMode === 'PREVIEW_ONLY') throw Object.assign(new Error('A preview-only restore cannot be executed.'), { statusCode: 400 }); if (restore.status !== 'APPROVED' && !(actor.role === 'TENANT_ADMIN' && selfServiceEnabled() && restore.status === 'PREVIEW_READY')) throw Object.assign(new Error('Approved restore is required before execution.'), { statusCode: 409 }); if (restore.restoreType === 'FULL_PLATFORM' && (!mfaVerified || actor.role !== 'SUPER_ADMIN')) throw Object.assign(new Error('Full-platform restore requires verified MFA.'), { statusCode: 403 }); const jobId = `restore-execution-${restore._id}`; await enqueue({ queue: QUEUES.RESTORE_EXECUTION, jobName: 'restore-execution', jobId, data: { restoreId: String(restore._id) } }); await restore.updateOne({ $set: { status: 'QUEUED', jobId } }); return RestoreRecord.findById(restore._id);
};
