// Canonical AI operations — application code requests these, never provider names.
export const AI_OPERATIONS = Object.freeze({
  QUESTION_GENERATION: 'QUESTION_GENERATION',
  CONTENT_GROUNDED_QUESTION_GENERATION: 'CONTENT_GROUNDED_QUESTION_GENERATION',
  QUESTION_REGENERATION: 'QUESTION_REGENERATION',
  QUESTION_REPAIR: 'QUESTION_REPAIR',
  QUESTION_IMPORT_ASSISTANCE: 'QUESTION_IMPORT_ASSISTANCE',
  QUESTION_CLASSIFICATION: 'QUESTION_CLASSIFICATION',
  COGNITIVE_CLASSIFICATION: 'COGNITIVE_CLASSIFICATION',
  BLOOM_CLASSIFICATION: 'BLOOM_CLASSIFICATION',
  QUESTION_EXPLANATION_GENERATION: 'QUESTION_EXPLANATION_GENERATION',
  QUESTION_IMAGE_GENERATION: 'QUESTION_IMAGE_GENERATION',
  EMBEDDING: 'EMBEDDING',
  HANDWRITING_EXTRACTION: 'HANDWRITING_EXTRACTION',
  ANSWER_SCRIPT_IDENTITY_EXTRACTION: 'ANSWER_SCRIPT_IDENTITY_EXTRACTION',
  ANSWER_SCRIPT_VISION: 'ANSWER_SCRIPT_VISION',
  ANSWER_TEXT_EVALUATION: 'ANSWER_TEXT_EVALUATION',
  ANSWER_RUBRIC_EVALUATION: 'ANSWER_RUBRIC_EVALUATION',
  ANSWER_IMAGE_EVALUATION: 'ANSWER_IMAGE_EVALUATION',
  DIAGRAM_RESPONSE_EVALUATION: 'DIAGRAM_RESPONSE_EVALUATION',
  VISUAL_RESPONSE_EVALUATION: 'VISUAL_RESPONSE_EVALUATION',
  FORMATIVE_ANSWER_FEEDBACK: 'FORMATIVE_ANSWER_FEEDBACK',
  MISCONCEPTION_ANALYSIS: 'MISCONCEPTION_ANALYSIS',
  EVALUATION_EXPLANATION: 'EVALUATION_EXPLANATION',
  GUIDELINE_INTERPRETATION: 'GUIDELINE_INTERPRETATION',
  CONTENT_METADATA_ENRICHMENT: 'CONTENT_METADATA_ENRICHMENT',
});

export const AI_PROVIDER_IDS = Object.freeze({
  OPENAI: 'openai',
  GEMINI: 'gemini',
  MOCK_OPENAI: 'mock_openai',
  MOCK_GEMINI: 'mock_gemini',
});

export const AI_ERROR_CODES = Object.freeze({
  AI_PROVIDER_NOT_CONFIGURED: 'AI_PROVIDER_NOT_CONFIGURED',
  AI_PROVIDER_UNAVAILABLE: 'AI_PROVIDER_UNAVAILABLE',
  AI_RATE_LIMITED: 'AI_RATE_LIMITED',
  AI_TIMEOUT: 'AI_TIMEOUT',
  AI_INVALID_RESPONSE: 'AI_INVALID_RESPONSE',
  AI_SAFETY_BLOCKED: 'AI_SAFETY_BLOCKED',
  AI_OUTPUT_VALIDATION_FAILED: 'AI_OUTPUT_VALIDATION_FAILED',
  AI_INPUT_TOO_LARGE: 'AI_INPUT_TOO_LARGE',
  AI_OPERATION_UNSUPPORTED: 'AI_OPERATION_UNSUPPORTED',
});

export class AIEngineError extends Error {
  constructor(code, message, { provider, operation, cause } = {}) {
    super(message);
    this.name = 'AIEngineError';
    this.code = code;
    this.provider = provider || '';
    this.operation = operation || '';
    this.cause = cause || null;
  }
}
